apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: cloud
type: Opaque
stringData:
  mariadb-root-password: rootpass123
  mariadb-password: userpass123
  mariadb-user: nextcloud
  mariadb-database: nextcloud
  host: mariadb
