apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: cloud
type: Opaque
stringData:
  mariadb-root-password: rootpass123
  mariadb-password: userpass123
  mariadb-user: nextcloud
  mariadb-database: nextcloud
  redis-password: 
  host: mariadb #forgor
