apiVersion: v1
kind: Secret
metadata:
  name: sys-cloud-secret
  namespace: cloud
type: Opaque
stringData:
  username: admin
  password: admin123
  # token: dummy-token  # optional, can remove if unused
