apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: cloud
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/mariadb"
