apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  namespace: cloud
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/nextcloud"
