# -*- mode: ruby -*-
# vi: set ft=ruby :

# Set default provider
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
ENV['LIBVIRT_DEFAULT_URI'] = 'qemu:///system'

# Nodes
nodes = [
  { :hostname => "masternode", :ip => "192.168.133.80" },
  { :hostname => "workernode", :ip => "192.168.133.81" },
]

Vagrant.configure("2") do |config|
  
  # Base box and provider - Changed to Ubuntu
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_check_update = false
  
  # Global libvirt provider configuration
  config.vm.provider :libvirt do |lv|
    lv.qemu_use_session = false
    lv.driver = "kvm"
    lv.uri = "qemu:///system"
    lv.machine_type = "q35"
    lv.cpu_mode = "host-passthrough"
    lv.nested = true
    lv.memory = 2048
    lv.cpus = 2
    lv.storage_pool_name = "default"
    lv.disk_driver :cache => 'writethrough'
  end
  # Provisioning
  nodes.each do |conf|
    config.vm.define conf[:hostname] do |node|
      # Hostname, disable synced folder and network
      node.vm.hostname = conf[:hostname]
      node.vm.synced_folder ".", "/vagrant", disabled: true
      
      # Network configuration
      node.vm.network :private_network,
                      :ip => conf[:ip],
                      :libvirt__network_name => 'net-vm'
      
      # Common provisioning
      node.vm.provision :shell,
                        :path => './config_bash/step1_general_setup.sh',
                        :args => [ conf[:ip] ]
      # Docker files
      node.vm.provision :file,
                        :source => "./ompi_osu_docker",
                        :destination => "/home/vagrant/"
      # Master node provisioning
      if conf[:hostname] == "masternode"
        node.vm.provision :shell,
                          :path => './config_bash/step2_master_setup.sh',
                          :privileged => true
        node.vm.provision :file,
                          :source => "./config_bash/flannel_setup.sh",
                          :destination => "/home/vagrant/"
        node.vm.provision :file,
                          :source => "./config_bash/mpi_setup.sh",
                          :destination => "/home/vagrant/"
        node.vm.provision :file,
                          :source => "./define_benchmark",
                          :destination => "/home/vagrant/"
      end
      # Worker node provisioning
      if conf[:hostname] == "workernode"
        node.vm.provision :shell,
                          :path => './config_bash/step3_worker_setup.sh',
                          :privileged => true
      end
      # Copy credentials for non-root user
      node.vm.provision :shell,
                        :path => './config_bash/set_access.sh',
                        :privileged => true
      # Install docker MPI images
      node.vm.provision :shell,
                        :path => './config_bash/define_tool_docker.sh',
                        :privileged => true
    end
  end
end
